name: Go

on:
  push:
    branches: [ "master", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...


    - name: Build Binary
      run: |
        go build -o simplemath .

    - name: Upload Binary to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_DEFAULT_REGION: "eu-central-1"
      run: |
        aws s3 cp simplemath s3://${{ secrets.TARGET_BUCKET }}/
  deploy:
    needs: build  # This ensures deploy runs only after build is successful
    runs-on: ubuntu-latest
    steps:
    - name: Download S3
      uses: joutvhu/download-s3@v1.0.0
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_KEY }}
        aws_region: "ap-south-1"  # Make sure this matches your S3 bucket region
        aws_bucket: ${{ secrets.TARGET_BUCKET }}
        target: .  # Downloads to current directory